docker_apt_gpg_key: 'https://download.docker.com/linux/debian/gpg'
docker_apt_repository: 'deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable'
docker_install_compose: false

devture_playbook_help_container_retries_delay: '10'
devture_playbook_help_container_retries_count: '10'

tawkie_panel_host: 'staging.tawkie.fr'

tawkie_mail_username: '{{ secret_tawkie_mail_username }}'
tawkie_mail_password: '{{ secret_tawkie_mail_password }}'
tawkie_mail_uri: 'smtps://{{ tawkie_mail_username }}:{{ tawkie_mail_password }}@smtp.tem.scw.cloud:465/'

tawkie_kratos_docker_image: 'oryd/kratos:v0.13.0'
tawkie_kratos_public_base_url: 'http://127.0.0.1:4433/'
tawkie_kratos_admin_base_url: 'http://127.0.0.1:4434/'
tawkie_kratos_selfservice_base_url: 'http://127.0.0.1:4455'
tawkie_kratos_secrets_cookie: '{{ secret_tawkie_kratos_secrets_cookie }}'
tawkie_kratos_secrets_cipher: '{{ secret_tawkie_kratos_secrets_cipher }}'
tawkie_kratos_bcrypt_cost: '11'
tawkie_kratos_courier_smtp_uri: '{{ tawkie_mail_uri }}'

tawkie_hydra_host: 'auth.{{ tawkie_panel_host }}'
tawkie_hydra_docker_image: 'oryd/hydra:v2.2'
tawkie_hydra_postgres_password: '{{ secret_tawkie_hydra_postgres_password }}'
tawkie_hydra_postgres_uri: 'postgres://hydra:{{ tawkie_hydra_postgres_password }}@{{ devture_postgres_container_network }}:5432/hydra?sslmode=disable'
tawkie_hydra_secrets_system: '{{ secret_tawkie_hydra_secrets_system }}'
tawkie_hydra_oidc_subject_identifiers_pairwise_salt: '{{ secret_tawkie_hydra_oidc_subject_identifiers_pairwise_salt }}'
tawkie_hydra_urls_self_issuer: 'https://{{ tawkie_hydra_host }}'
tawkie_hydra_urls_consent: 'https://{{ tawkie_panel_host }}/consent' # TODO
tawkie_hydra_urls_login: 'https://{{ tawkie_panel_host }}/login'
tawkie_hydra_urls_logout: 'https://{{ tawkie_panel_host }}/api/.ory/self-service/logout'

tawkie_kratos_panel_repo_username: '{{ secret_tawkie_kratos_panel_repo_username }}'
tawkie_kratos_panel_repo_password: '{{ secret_tawkie_kratos_panel_repo_password }}'
tawkie_kratos_panel_repo_url: 'https://{{ tawkie_kratos_panel_repo_username | urlencode }}:{{ tawkie_kratos_panel_repo_password | urlencode }}@github.com/Tawkie/kratos-panel.git'
tawkie_kratos_panel_repo_version: 'docker'


tawkie_nats_docker_image: 'nats:2.9.19-scratch'
tawkie_nats_container_network: 'tawkie-nats'

tawkie_traefik_docker_image: 'traefik:v2.10.3'
tawkie_traefik_container_network: 'tawkie-traefik'

tawkie_wireguard_admin_docker_image: 'linuxserver/wireguard:1.0.20210914'
tawkie_wireguard_admin_container_network: 'tawkie-wireguard-admin'
tawkie_wireguard_admin_listen_port: '5530'
tawkie_wireguard_admin_conf_interface_ip: '10.0.4.1'
tawkie_wireguard_admin_conf_interface_private_key: '{{ secret_tawkie_wireguard_admin_conf_interface_private_key }}'
# interface public key : vDFTT+5yIYK1LOicDkLAUO0O4MoSZ3VJVMmthpyeyW0=
tawkie_wireguard_admin_conf_peer_ip: '10.0.4.2'
tawkie_wireguard_admin_conf_peer_public_key: '{{ secret_tawkie_wireguard_admin_conf_peer_public_key }}'
# peer private key : see matrix ansible deploy

devture_postgres_connection_password: "{{ secret_postgres_db_default_password }}"
devture_postgres_base_path: "/postgres"
devture_postgres_managed_databases_auto: |
  {{
    [{
      'name': 'kratos',
      'username': 'kratos',
      'password': secret_postgres_db_kratos_password
    },{
      'name': 'hydra',
      'username': 'hydra',
      'password': tawkie_hydra_postgres_password
    }]
  }}


devture_systemd_service_manager_enabled: true
devture_systemd_service_manager_services_autostart_enabled: true
devture_systemd_service_manager_services_list_auto: |
  {{
    ([{'name': 'devture-postgres.service', 'priority': 1000}])
    +
    ([{'name': 'tawkie-kratos.service', 'priority': 2000}])
    +
    ([{'name': 'tawkie-nats.service', 'priority': 3000}])
    +
    ([{'name': 'tawkie-kratos-panel.service', 'priority': 4000}])
    +
    ([{'name': 'tawkie-hydra.service', 'priority': 4500}])
    +
    ([{'name': 'tawkie-wireguard-admin.service', 'priority': 5000}])
    +
    ([{'name': 'tawkie-traefik.service', 'priority': 10000}])
  }}
