docker_apt_gpg_key: 'https://download.docker.com/linux/debian/gpg'
docker_apt_repository: 'deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable'
docker_install_compose: false

devture_playbook_help_container_retries_delay: '10'
devture_playbook_help_container_retries_count: '10'

devture_postgres_connection_password: "{{ secret_postgres_db_default_password }}"
devture_postgres_base_path: "/postgres"
devture_postgres_managed_databases_auto: |
  {{
    [{
      'name': 'kratos',
      'username': 'kratos',
      'password': secret_postgres_db_kratos_password
    }]
  }}

tawkie_kratos_docker_image: 'oryd/kratos:v0.13.0'

tawkie_nats_docker_image: 'nats:2.9.19-scratch'
tawkie_nats_container_network: 'tawkie-nats'

devture_systemd_service_manager_enabled: true
devture_systemd_service_manager_services_autostart_enabled: true
devture_systemd_service_manager_services_list_auto: |
  {{
    ([{'name': 'devture-postgres.service', 'priority': 10000}])
    +
    ([{'name': 'tawkie-kratos.service', 'priority': 9000}])
    +
    ([{'name': 'tawkie-nats.service', 'priority': 8000}])
  }}
