docker_apt_gpg_key: 'https://download.docker.com/linux/debian/gpg'
docker_apt_repository: 'deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable'
docker_install_compose: false

devture_playbook_help_container_retries_delay: '10'
devture_playbook_help_container_retries_count: '10'

devture_postgres_connection_password: "{{ secret_postgres_db_default_password }}"
devture_postgres_base_path: "/postgres"
devture_postgres_managed_databases_auto: |
  {{
    [{
      'name': 'kratos',
      'username': 'kratos',
      'password': secret_postgres_db_kratos_password
    }]
  }}

tawkie_panel_host: 'staging.tawkie.fr'

tawkie_mail_username: '{{ secret_tawkie_mail_username }}'
tawkie_mail_password: '{{ secret_tawkie_mail_password }}'
tawkie_mail_uri: 'smtps://{{ tawkie_mail_username }}:{{ tawkie_mail_password }}@smtp.tem.scw.cloud:465/'

tawkie_kratos_docker_image: 'oryd/kratos:v0.13.0'
tawkie_kratos_public_base_url: 'http://127.0.0.1:4433/'
tawkie_kratos_admin_base_url: 'http://127.0.0.1:4434/'
tawkie_kratos_selfservice_base_url: 'http://127.0.0.1:4455'
tawkie_kratos_secrets_cookie: '{{ secret_tawkie_kratos_secrets_cookie }}'
tawkie_kratos_secrets_cipher: '{{ secret_tawkie_kratos_secrets_cipher }}'
tawkie_kratos_bcrypt_cost: '11'
tawkie_kratos_courier_smtp_uri: '{{ tawkie_mail_uri }}'

tawkie_kratos_panel_repo_username: '{{ secret_tawkie_kratos_panel_repo_username }}'
tawkie_kratos_panel_repo_password: '{{ secret_tawkie_kratos_panel_repo_password }}'
tawkie_kratos_panel_repo_url: 'https://{{ tawkie_kratos_panel_repo_username | urlencode }}:{{ tawkie_kratos_panel_repo_password | urlencode }}@github.com/Tawkie/kratos-panel.git'
tawkie_kratos_panel_repo_version: 'docker'


tawkie_nats_docker_image: 'nats:2.9.19-scratch'
tawkie_nats_container_network: 'tawkie-nats'

tawkie_traefik_docker_image: 'traefik:v2.10.3'
tawkie_traefik_container_network: 'tawkie-traefik'

devture_systemd_service_manager_enabled: true
devture_systemd_service_manager_services_autostart_enabled: true
devture_systemd_service_manager_services_list_auto: |
  {{
    ([{'name': 'devture-postgres.service', 'priority': 1000}])
    +
    ([{'name': 'tawkie-kratos.service', 'priority': 2000}])
    +
    ([{'name': 'tawkie-nats.service', 'priority': 3000}])
    +
    ([{'name': 'tawkie-kratos-panel.service', 'priority': 4000}])
    +
    ([{'name': 'tawkie-traefik.service', 'priority': 10000}])
  }}
tawkie_staticapache2_uid: 'staticapache2'
tawkie_staticapache2_gid: 'staticapache2'
tawkie_staticapache2_container_network: 'tawkie-staticapache2'
tawkie_staticapache2_docker_image: 'httpd:2.4'