docker_apt_gpg_key: 'https://download.docker.com/linux/debian/gpg'
docker_apt_repository: 'deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable'
docker_install_compose: false

devture_playbook_help_container_retries_delay: '10'
devture_playbook_help_container_retries_count: '10'
devture_postgres_connection_password: "{{ secret_postgres_db_default_password }}"
devture_postgres_uid: 'postgres'
devture_postgres_gid: 'postgres'
