---

- name: Ensure tawkie group is created
  ansible.builtin.group:
    name: "tawkie"
    state: present
  tags:
    - setup-all


- name: Ensure tawkie user is created
  ansible.builtin.user:
    name: "tawkie"
    state: present
    group: "tawkie"
    system: true
  tags:
    - setup-all

- name: Ensure Postgres group is created
  ansible.builtin.group:
    name: "postgres"
    state: present
  register: postgres_group
  tags:
    - setup-all
    - setup-postgres


- name: Ensure Postgres user is created
  ansible.builtin.user:
    name: "postgres"
    state: present
    group: "postgres"
    home: "/postgres"
    create_home: false
    system: true
  register: postgres_user
  tags:
    - setup-postgres
    - setup-all


- name: Initialize devture_postgres_uid and devture_postgres_gid
  ansible.builtin.set_fact:
    devture_postgres_uid: "{{ postgres_user.uid }}"
    devture_postgres_gid: "{{ postgres_group.gid }}"
  tags:
    - setup-all
    - setup-postgres


- name: Ensure Kratos group is created
  ansible.builtin.group:
    name: "kratos"
    state: present
  tags:
    - setup-all
    - setup-kratos


- name: Ensure Kratos user is created
  ansible.builtin.user:
    name: "kratos"
    state: present
    group: "kratos"
    system: true
  tags:
    - setup-kratos
    - setup-all

- name: Ensure Tawkie directory is created
  ansible.builtin.file:
    path: /tawkie
    state: directory
    owner: tawkie
    group: tawkie
    mode: '0771'
  tags:
    - setup-all
