---

- name: Ensure tawkie group is created
  ansible.builtin.group:
    name: "tawkie"
    state: present
  tags:
    - setup-all


- name: Ensure tawkie user is created
  ansible.builtin.user:
    name: "tawkie"
    state: present
    group: "tawkie"
    system: true
  tags:
    - setup-all

- name: Ensure Postgres group is created
  ansible.builtin.group:
    name: "postgres"
    state: present
  register: postgres_group
  tags:
    - setup-all
    - setup-postgres


- name: Ensure Postgres user is created
  ansible.builtin.user:
    name: "postgres"
    state: present
    group: "postgres"
    home: "/postgres"
    create_home: false
    system: true
  register: postgres_user
  tags:
    - setup-postgres
    - setup-all


- name: Initialize devture_postgres_uid and devture_postgres_gid
  ansible.builtin.set_fact:
    devture_postgres_uid: "{{ postgres_user.uid }}"
    devture_postgres_gid: "{{ postgres_group.gid }}"
  tags:
    - setup-all
    - setup-postgres


- name: Ensure Kratos group is created
  ansible.builtin.group:
    name: "kratos"
    state: present
  register: kratos_group
  tags:
    - setup-all
    - setup-kratos


- name: Ensure Kratos user is created
  ansible.builtin.user:
    name: "kratos"
    state: present
    group: "kratos"
    system: true
    shell: '/bin/false'
  register: kratos_user
  tags:
    - setup-kratos
    - setup-all

- name: Initialize tawkie_kratos_uid and tawkie_kratos_gid
  ansible.builtin.set_fact:
    tawkie_kratos_uid: "{{ kratos_user.uid }}"
    tawkie_kratos_gid: "{{ kratos_group.gid }}"
  tags:
    - setup-all
    - setup-kratos

- name: Ensure Hydra group is created
  ansible.builtin.group:
    name: "hydra"
    state: present
  register: hydra_group
  tags:
    - setup-all
    - setup-hydra


- name: Ensure Hydra user is created
  ansible.builtin.user:
    name: "hydra"
    state: present
    group: "hydra"
    system: true
    shell: '/bin/false'
  register: hydra_user
  tags:
    - setup-hydra
    - setup-all

- name: Initialize tawkie_hydra_uid and tawkie_hydra_gid
  ansible.builtin.set_fact:
    tawkie_hydra_uid: "{{ hydra_user.uid }}"
    tawkie_hydra_gid: "{{ hydra_group.gid }}"
  tags:
    - setup-all
    - setup-hydra

- name: Ensure Kratos Panel group is created
  ansible.builtin.group:
    name: "kratos-panel"
    state: present
  register: kratos_panel_group
  tags:
    - setup-all
    - setup-kratos-panel

- name: Ensure Kratos Panel user is created
  ansible.builtin.user:
    name: "kratos-panel"
    state: present
    group: "kratos-panel"
    system: true
    shell: '/bin/false'
  register: kratos_panel_user
  tags:
    - setup-kratos-panel
    - setup-all

- name: Initialize tawkie_kratos_panel_uid and tawkie_kratos_panel_gid
  ansible.builtin.set_fact:
    tawkie_kratos_panel_uid: "{{ kratos_panel_user.uid }}"
    tawkie_kratos_panel_gid: "{{ kratos_panel_group.gid }}"
  tags:
    - setup-all
    - setup-kratos-panel

- name: Ensure Tawkie directory is created
  ansible.builtin.file:
    path: /tawkie
    state: directory
    owner: tawkie
    group: tawkie
    mode: '0771'
  tags:
    - setup-all

- name: Ensure Tawkie docker building directory is created
  ansible.builtin.file:
    path: /tawkie-docker-build
    state: directory
    owner: tawkie
    group: tawkie
    mode: '0771'
  tags:
    - setup-all
    - setup-kratos-panel

- name: Ensure NATS group is created
  ansible.builtin.group:
    name: "nats"
    state: present
  register: nats_group
  tags:
    - setup-all
    - setup-nats


- name: Ensure NATS user is created
  ansible.builtin.user:
    name: "nats"
    state: present
    group: "nats"
    system: true
    shell: '/bin/false'
  register: nats_user
  tags:
    - setup-all
    - setup-nats

- name: Initialize tawkie_nats_uid and tawkie_nats_gid
  ansible.builtin.set_fact:
    tawkie_nats_uid: "{{ nats_user.uid }}"
    tawkie_nats_gid: "{{ nats_group.gid }}"
  tags:
    - setup-all
    - setup-nats

- name: Ensure Traefik group is created
  ansible.builtin.group:
    name: "docker"
    state: present
  register: traefik_group
  tags:
    - setup-all
    - setup-traefik


- name: Ensure Traefik user is created
  ansible.builtin.user:
    name: "traefik"
    state: present
    group: "docker"
    system: true
    shell: '/bin/false'
  register: traefik_user
  tags:
    - setup-all
    - setup-traefik


- name: Initialize tawkie_traefik_uid and tawkie_traefik_gid
  ansible.builtin.set_fact:
    tawkie_traefik_uid: "{{ traefik_user.uid }}"
    tawkie_traefik_gid: "{{ traefik_group.gid }}"
  tags:
    - setup-all
    - setup-traefik

- name: Ensure wireguard-admin group is created
  ansible.builtin.group:
    name: "wireguard-admin"
    state: present
  register: wireguard_admin_group
  tags:
    - setup-all
    - setup-wireguard-admin

- name: Ensure wireguard-admin user is created
  ansible.builtin.user:
    name: "wireguard-admin"
    state: present
    group: "wireguard-admin"
    system: true
    shell: '/bin/false'
  register: wireguard_admin_user
  tags:
    - setup-all
    - setup-wireguard-admin

- name: Initialize tawkie_wireguard_admin_uid and tawkie_wireguard_admin_gid
  ansible.builtin.set_fact:
    tawkie_wireguard_admin_uid: "{{ wireguard_admin_user.uid }}"
    tawkie_wireguard_admin_gid: "{{ wireguard_admin_group.gid }}"
  tags:
    - setup-all
    - setup-wireguard-admin

- name: Ensure matrix-signup group is created
  ansible.builtin.group:
    name: "matrix-signup"
    state: present
  register: matrix_signup_group
  tags:
    - setup-all
    - setup-matrix-signup

- name: Ensure matrix-signup user is created
  ansible.builtin.user:
    name: "matrix-signup"
    state: present
    group: "matrix-signup"
    system: true
    shell: '/bin/false'
  register: matrix_signup_user
  tags:
    - setup-all
    - setup-matrix-signup

- name: Initialize tawkie_matrix_signup_uid and tawkie_matrix_signup_gid
  ansible.builtin.set_fact:
    tawkie_matrix_signup_uid: "{{ matrix_signup_user.uid }}"
    tawkie_matrix_signup_gid: "{{ matrix_signup_group.gid }}"
  tags:
    - setup-all
    - setup-matrix-signup
