---

- name: Ensure Postgres group is created
  ansible.builtin.group:
    name: "{{ devture_postgres_gid }}"
    state: present
  tags:
    - setup-all
    - setup-postgres


- name: Ensure Postgres user is created
  ansible.builtin.user:
    name: "{{ devture_postgres_uid }}"
    state: present
    group: "{{ devture_postgres_gid }}"
    system: true
  tags:
    - setup-postgres
    - setup-all
