---

- name: Ensure tawkie group is created
  ansible.builtin.group:
    name: "tawkie"
    state: present
  tags:
    - setup-all


- name: Ensure tawkie user is created
  ansible.builtin.user:
    name: "tawkie"
    state: present
    group: "tawkie"
    system: true
  tags:
  - setup-all

- name: Ensure Postgres group is created
  ansible.builtin.group:
    name: "{{ devture_postgres_gid }}"
    state: present
  tags:
    - setup-all
    - setup-postgres


- name: Ensure Postgres user is created
  ansible.builtin.user:
    name: "{{ devture_postgres_uid }}"
    state: present
    group: "{{ devture_postgres_gid }}"
    system: true
  tags:
    - setup-postgres
    - setup-all

- name: Ensure Tawkie directory is created
  ansible.builtin.file:
    path: /tawkie
    state: directory
    owner: tawkie
    group: tawkie
    mode: '0771'
  tags:
    - setup-all
