- name: Get system facts
  ansible.builtin.setup:
    filter: ansible_distribution*
  tags:
    - setup-all

- name: Check Debian 12
  ansible.builtin.fail:
    msg: "This playbook requires Debian 12, but the target system is running {{ ansible_distribution }} version {{ ansible_distribution_version }}"
  when: "'Debian' in ansible_distribution and '12' not in ansible_distribution_version"
  tags:
    - setup-all

- name: Check if PasswordAuthentication is set to 'no'
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  register: password_auth
  tags:
    - setup-all

- name: Fail if SSH password authentication is enabled
  ansible.builtin.fail:
    msg: "SSH password authentication is enabled. Please disable it by setting 'PasswordAuthentication no' in /etc/ssh/sshd_config."
  when: "not password_auth"
  tags:
    - setup-all
      
# Required by chmod
- name: Install acl package
  ansible.builtin.apt:
    name: acl
    state: present
  tags:
    - setup-all
    - setup-kratos-panel

- name: Include user creation tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/create_users.yml"
  tags:
    - setup-all
    - setup-postgres
    - setup-kratos
    - setup-kratos-panel
    - setup-nats
    - setup-traefik
    - setup-wireguard-admin
