- name: Ensure system setup
  hosts: transverse
  become: true
  roles:
    - basic_tools
    - ntfy
    - geerlingguy.docker
    - com.devture.ansible.role.systemd_docker_base
    - com.devture.ansible.role.postgres
    - ory-kratos
    - ory-hydra
    - kratos-panel
    - nats
    - traefik
    - wireguard-admin

    - when: devture_systemd_service_manager_enabled | bool
      role: com.devture.ansible.role.systemd_service_manager
