- name: Ensure system setup
  hosts: transverse
  become: true
  roles:
    - basic_tools
    - geerlingguy.docker
    - com.devture.ansible.role.systemd_docker_base
    - com.devture.ansible.role.postgres
