- name: Include install tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup-install.yml"
  tags:
    - setup-all
    - setup-staticapache2
    
- name: Include css tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/css.yml"
  tags:
    - setup-all
    - setup-staticapache2

- name: Include website tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/website.yml"
  tags:
    - setup-all
    - setup-staticapache2