- name: Ensure Hugo image is pulled
  community.docker.docker_image:
    name: "{{ tawkie_staticapache2_hugo_docker_image }}"
    source: "pull"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed
  tags:
    - setup-all
    - setup-staticapache2

- name: Ensure Tailwindcss image is pulled
  community.docker.docker_image:
    name: "{{ tawkie_staticapache2_tailwindcss_docker_image }}"
    source: "pull"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed
  tags:
    - setup-all
    - setup-staticapache2

- name: Build website CSS with Tailwindcss
  community.docker.docker_container:
    name: hugo_build
    image: "{{ tawkie_staticapache2_tailwindcss_docker_image }}"
    command: '-i ./assets/css/input.css -o ./assets/css/index.css --jit --minify'
    user: "{{ tawkie_staticapache2_uid }}:{{ tawkie_staticapache2_gid }}"
    volumes:
      - "/tawkie/staticapache2/source/:/project"
    auto_remove: true
  tags:
    - setup-all
    - setup-staticapache2

- name: Build website with Hugo
  community.docker.docker_container:
    name: hugo_build
    image: "{{ tawkie_staticapache2_hugo_docker_image }}"
    command: '--gc --minify -d public/ --baseURL {{ tawkie_static_apache2_website_baseurl }}'
    user: "{{ tawkie_staticapache2_uid }}:{{ tawkie_staticapache2_gid }}"
    volumes:
      - "/tawkie/staticapache2/source/:/src"
    auto_remove: true
  tags:
    - setup-all
    - setup-staticapache2
