- name: Ensure NATS image is pulled
  community.docker.docker_image:
    name: "{{ tawkie_nats_docker_image }}"
    source: "pull"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed
  tags:
    - setup-all
    - setup-nats


- name: Ensure NATS systemd template set
  ansible.builtin.template:
    src: "{{ role_path }}/templates/tawkie-nats.service.j2"
    dest: "/etc/systemd/system/tawkie-nats.service"
    mode: "0600"
    owner: "root"
  tags:
    - setup-all
    - setup-nats

- name: Ensure NATS container network is created
  community.general.docker_network:
    name: "{{ tawkie_nats_container_network }}"
    driver: bridge
  tags:
    - setup-all
    - setup-nats
