- name: Ensure Traefik image is pulled
  community.docker.docker_image:
    name: "{{ tawkie_traefik_docker_image }}"
    source: "pull"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed
  tags:
    - setup-all
    - setup-traefik


- name: Ensure Traefik systemd template set
  ansible.builtin.template:
    src: "{{ role_path }}/templates/tawkie-traefik.service.j2"
    dest: "/etc/systemd/system/tawkie-traefik.service"
    mode: "0600"
    owner: "root"
  tags:
    - setup-all
    - setup-traefik

- name: Ensure Traefik container network is created
  community.general.docker_network:
    name: "{{ tawkie_traefik_container_network }}"
    driver: bridge
  tags:
    - setup-all
    - setup-traefik

- name: Ensure Traefik paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0500"
    owner: "traefik"
    group: "traefik"
  with_items:
    - "/tawkie/traefik"
  tags:
    - setup-all
    - setup-traefik


- name: Ensure Traefik config template set
  ansible.builtin.template:
    src: "{{ role_path }}/templates/config.toml.j2"
    dest: "/tawkie/traefik/config.toml"
    mode: "0400"
    owner: "traefik"
    group: "traefik"
  tags:
    - setup-all
    - setup-traefik


- name: Ensure Traefik dynamic service templates set
  ansible.builtin.template:
    src: "{{ role_path }}/templates/dynamic/{{ item }}.toml.j2"
    dest: "/tawkie/traefik/dynamic/{{ item }}.toml"
    mode: "0400"
    owner: "traefik"
    group: "traefik"
  loop:
    - kratos
    - kratos-panel
  tags:
    - setup-all
    - setup-traefik
